# Generated by Django 2.0.1 on 2018-01-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_office', '0002_auto_20180129_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='last_tech_exam',
        ),
    ]
