# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police_office', '0003_remove_car_last_tech_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceCar',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=8)),
                ('model', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('production_year', models.DateField()),
                ('engine_number', models.CharField(max_length=20)),
                ('engine_capacity', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('special_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name=b'owner',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='policecar',
            name='station_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_office.PoliceStation'),
        ),
    ]
