# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'verbose_name_plural': 'Inscurance Companies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='street_addres',
            new_name='street_address',
        ),
    ]
