# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_office', '0002_auto_20171110_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='loacal_number',
            new_name='local_number',
        ),
    ]
