# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_office', '0004_healthexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_person', models.CharField(blank=True, max_length=70)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='district_office.Person')),
            ],
            options={
                'verbose_name_plural': 'Technical Examinations',
            },
        ),
    ]
