# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_office', '0005_technicalexamination'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('S', 'Stolen'), ('F', 'Found'), ('N', 'Normal')], default='N', max_length=1),
        ),
    ]
