# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_office', '0006_car_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('Stolen', 'Stolen'), ('Found', 'Found'), ('Normal', 'Normal')], default='Normal', max_length=6),
        ),
    ]
